
//import { Html, Head, Main, NextScript } from 'next/document'

//import Head from 'next/head'
//import Script from 'next/script'
import { Manrope } from 'next/font/google'
import Providers from './providers'
import './globals.css'
import { createUsers } from "@/lib/server-actions"
import { prisma } from "@/lib/prisma";
import Menubar from '../components/navbar'
//import { bot } from "./bot"
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'Гаражи',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // <html className={manrope.variable} lang="en"  suppressHydrationWarning> 
    <html className='light' lang="en" suppressHydrationWarning> 
      <head>
        {/* <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive"></Script> */}
      </head>
      <body className='wrapper'> 
        {/* <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" /> */}
            <Providers>
                  {children}
            </Providers>
          </body>
      </html >
  )
}
